### ISSUE TITLE
Zmenšit úvodní obrázek?

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#11]
Suoučasná úvodní fotka má 3000 × 2000 px a 3 MB. Není to trochu moc? Nestačí něco jako 1920 × xy?

**Comment by mukrop** [comment]
Ak ju budete zmensovat, vyuzite prilezitost a zmensenim ju trochu doostrite. Na mojom aktualnom monitore (1600x900) vyzera "rozmazane" a teda nie uplne dobre (a nebude to asi rozlisenim ale fotkou samotnou).
