### ISSUE TITLE
Obfuskovat e-mail

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#14]
Navrhuji minimálně `k<span style="display: none;">loskarlos</span>scuk@fi.muni.cz`. Pokud chceš e-mail klikací, doporučuji javascript obfuskaci, viz např. web Soba.

**Comment by malinajan** [comment]
No, teď ten spambot zjistí e-mail z `mailto:`, ne? :)

**Comment by Krejdom** [comment]
`mailto:` mi osobně přijde strašně zbytečné, stejně to chci většinou jen zkopírovat (a nepoužívat mailové klienty na pc - stašně mě otravuje, když na to omylem kliknu a začne se mi něco divnýho otevírat) vy to někdo používáte?

**Comment by malinajan** [comment]
Já obvykle adresu opisuji nebo kopíruji. Za mě může jít `mailto:` klidně pryč.
