### ISSUE TITLE
Barevné tlačítko "Chci se zúčastnit"?

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#17]
Tlačítko na mě teď působí neaktivně. Vybarvit by default? Vybarvit on hover? Co si o tom myslí třeba @Krejdom nebo @GiraffeReversed?

**Comment by mukrop** [comment]
NAvrhujem default farebne, aby putalo viac pozornosti. A idealne aj nejaky hover, aby "reagovalo".

**Comment by GiraffeReversed** [comment]
Taky si myslím, že barevné tlačítko upoutá víc pozornosti. Myslím, že by bylo hezké, kdyby mělo jednu z barev (oranžová, zelená), a on hover by se změnilo na tu druhou (alespoň částečně by to zachovalo rovnováhu...).

**Comment by malinajan** [comment]
Anebo může být barva tlačítka náhodná, třeba:

```
if now.seconds % 2 == 0: color = ksi else color = ibis
```

:P
