### ISSUE TITLE
Přidat info o tom, kdo web vytvořil?

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#18]
Přidat někam do patičky "vytvořil XYZ", případně pod jakou licencí je poskytován obsah webu?

**Comment by zvizesna** [comment]
Co se licence týče, jde ti asi o fotky, že?
A pod jakou licencí chceme věci poskytovat?

**Comment by zvizesna** [comment]
Jinak autoři webu jsou uvedení v html meta tagu. Myslím, že psát autorství do patičky je divné.

**Comment by malinajan** [comment]
HTML meta tag nikdo moc nečte. Představ si, že web od tebe převezme jiná akce, chtěla bys, aby ta akce napsala, že jsi autorka designu, nebo je ti to úplně jedno? Viz např. převzatí designu KSI pro  http://ibis.sci.muni.cz/. Licence je také licence textů a třeba toho designu, obecně bych předpokládal licenci na kompletní html a css kód a fotky.

Např. KSI web je licencován pod CC BY-NC v4.0. Umožňuje tak vcelku pohodlně přebírat design, nebo třeba úlohy.

https://creativecommons.org/licenses/by-nc/4.0/

(To, že dáme web pod licencí CC BY-NC v4.0 neznamená, že jej nikdy nemůže používat komerční subjekt. Jen nám prostě musí napsat a my mu po schválení dáme kód pod licencí, kterou si vymyslíme.)

Já jsem klidně pro CC. @mukrop, @zvizesna: názory?

**Comment by mukrop** [comment]
CC je podla mna dobra a relativne flexibilna licencia. Uvadzat licenciu pramo na strankach je dobra prax (nie je to uplne bezne, ukazuje to, ze autor sa vyzna). Autora do paticky kludne ano, HTML meta naozaj necita nikto. Je na vas, ci tam date ako autora "K-SCUK", alebo priamo meno.

**Comment by zvizesna** [comment]
d13b81472344cb8f797b8866b429ac2d68f14e6d

**Comment by zvizesna** [comment]
95acb9be000ea2062ec79a1723ad05b2403aca9d
