### ISSUE TITLE
Vybraná položka checkboxu je podivně barevná

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#20]
Tohle se má dít? Vypadá to vážně divně.

![screenshot_20180329_215017](https://user-images.githubusercontent.com/12673442/38110248-3d2e649a-339b-11e8-8eb7-b048cdd4debb.png)

**Comment by zvizesna** [comment]
Ano, to je záměr. :D Proč ti to připadá divné? Chová se to logicky a má ti to vizuálně pomoct.

**Comment by malinajan** [comment]
Vizuálně mi pomůže to VELKÉ modré vlevo. To je snad dostatečné ne? Tohle je podle mě vážně divné, míchat tam další barvu. Doporučuji zeptat se na názory dalších lidí.

**Comment by zvizesna** [comment]
Checkboxy zřejmě vypadají v každém prohlížeči jinak. Běžněji vídám černé ticky, a tam to vypadá úplně v pohodě a vážně to usnadňuje čtení.
Je to mobil, nebo co používáš?

**Comment by malinajan** [comment]
Normální firefox na desktopu.

**Comment by zvizesna** [comment]
Zajímavé. Firefox u mě:
![ticks](https://user-images.githubusercontent.com/16738938/38111827-66e9509c-33a0-11e8-8b11-07d2db39a4a9.png)

**Comment by zvizesna** [comment]
Tak asi spíš OS.

**Comment by malinajan** [comment]
To só té windóse.

**Comment by malinajan** [comment]
U mě samozřejmě Debian <3.

**Comment by zvizesna** [comment]
Můžu si je nechat a zavřít to?

**Comment by malinajan** [comment]
No co mi zbývá... :P
