### ISSUE TITLE
Nekonzistentna paticka

### ISSUE THREAD

**Issue by mukrop** [zverinec/kscuk-web#23]
V paticke su 2 loga farebne (ksi, ibis), ostatne su biele. Zdalo by sa mi to lepsie konzistentne (osobne navrhujem vsetko biele a ak chcete, tak farebny hover, ale ten aj nemusi byt).

**Comment by malinajan** [comment]
Mně osobně barevný KSI a IBIS nevadí, vidím smysl v tom, že jsou to ty 2 hlavní semináře, které K-SCUK sdružuje. Hover vidím jako *nice-to-have*, rozhodně to ale momentálně nevidím jako prioritu.

**Comment by zvizesna** [comment]
Jak říká Honza; myšlenka byla taková, že KSI a IBIS jsou to hlavní, a proto budou barevně. Z jejich log je také vzatá zelená a oranžová, a pomocí log se k seminářům barvy dobře přiřadí. Taky se stránka barevně doplní / vyváží i dole. Kdyby byla barevná i ostatní loga, už by to neladilo, a kdyby byla všechna bílá, přišlo by mi to nezajímavé.
Protože je barevnost takhle asymetrická, nevěděla jsem, jak hover zařídit. Jestli je ale žádoucí, tak nad tím ještě popřemýšlím.
