### ISSUE TITLE
Zmena menu v hlavicke

### ISSUE THREAD

**Issue by mukrop** [zverinec/kscuk-web#24]
Ked otvorim stranku s prihlaskou, v hlavicke sa zmeni rozlozenie menu (zmizne polozka "zucastnit se"). Myslim si, ze menit menu nie je uplne dobra prax (preferoval by som ho vsade rovnake).

**Comment by Krejdom** [comment]
Další návrhy:

- zvýraznit aktuální navštívenou stránku  (jsem v archivu, je podbarven archiv)
- oddělat odkaz u aktuální návštívené stránky (už tam jsem - proč bych tam šla znovu?)
- přejmenovat sekci "Zúčastnit se" na "Registrace" (je to i nadpis na samotné stránce)
- přejmenovat sekci "O co jde" na "Informace" (protože o co jde je jen jedna část té sekce na webu + pak bude jednotnější menu - všechno jednoslovná podstatná jména)

**Comment by malinajan** [comment]
> zvýraznit aktuální navštívenou stránku (jsem v archivu, je podbarven archiv)

Jsem pro! U *O co jde* a *Orgové* to ale podle mě rozumě nejde (protože odkazují dolů na stránku), řešil bych to jen u *Zúčastnit se* a *Archív*.

> oddělat odkaz u aktuální návštívené stránky (už tam jsem - proč bych tam šla znovu?)

Tohle je podle mě zbytečně implementačně náročné. Běžné weby ten odkaz mají stále aktivní, jen je prostě podbarvený. Zmizení odkazu je nečekané chování.

> přejmenovat sekci "Zúčastnit se" na "Registrace" (je to i nadpis na samotné stránce)

Mně nevadí aktuální verze.

> přejmenovat sekci "O co jde" na "Informace" (protože o co jde je jen jedna část té sekce na webu + pak bude jednotnější menu - všechno jednoslovná podstatná jména)

Mně nevadí aktuální verze.

**Comment by zvizesna** [comment]
> oddělat odkaz u aktuální návštívené stránky (už tam jsem - proč bych tam šla znovu?)
To bylo původní chování, kvůli kterému bylo issue otevřeno.

Ok, položky menu přejmenuju.
