### ISSUE TITLE
Preihlasovaci formular na viac stran

### ISSUE THREAD

**Issue by mukrop** [zverinec/kscuk-web#25]
Ma dovod, ze prihlasovaci formular ma viac stran? Ak by tam bolo mnoho otazok, tak jasne, ale ked je na kazdej strane 1-3 otazky tak mi to uplne nedava zmysel.

**Comment by malinajan** [comment]
Když je formulář rozdělen na 3 strany, vyplníš první a myslíš si, že je to vše, klikneš na *Pokračovat*, pak vidíš další otázky, ale protože jsi už začal, formulář dotáhneš a přihlášku vyplníš.

Kdyby bylo vše na jedné straně, je podle mě výrazně vyšší vstupní laťka pro vyplnění.

Na druhou stranu, o počet účastníků se asi bát nemusíme. Na třetí stranu by možná stálo za to feature *snadno láká lidi* neničit jen kvůli tomu, že *zrovna teď* máme hodně řešitelů.

**Comment by zvizesna** [comment]
Souhlasím s Honzou.

**Comment by mukrop** [comment]
Ok.
