### ISSUE TITLE
"od neděle do neděle"?

### ISSUE THREAD

**Issue by mukrop** [zverinec/kscuk-web#26]
Uvodna stranka pomerne prominentne pise "od neděle do neděle". Ma to nejaky dovod? (akcie taketo veci zvycajne tak prominentne nepisu a nedela-nedela mi pride celkom standard -- key to bola streda-streda, prislo by mi to viac opodstatnene).

**Comment by malinajan** [comment]
Mně "od neděle do neděle" nevadí, ale když to tam nebude, tak mi to také nevadí.
