### ISSUE TITLE
Vyraznejsia zmienka o KSI/IBIS?

### ISSUE THREAD

**Issue by mukrop** [zverinec/kscuk-web#27]
V texte "O co jde?" by som mozno nejako vyraznejsie zmienil KSI/IBIS. Dat to ako preklik na stranky seminarov (a teda farebne)? Alebo vpravo vedla popisu dat loga KSI/IBIS (a mozno MU)?
(cisto moj subjektivny pocit)

**Comment by mukrop** [comment]
Inak ten text je hrozne dlhy a nestrukturovany (vyse 4 riadky maleho textu na velkom monitore). Nedali by sa nejako rozdelit? Napr. O co jde + Kdo za tim stoji + Co muzes zazit? (Alebo take nieco.)

**Comment by zvizesna** [comment]
@mukrop  @horacekj  Lepší?

**Comment by mukrop** [comment]
Opticky vyrazne lepsie :-}.

**Comment by zvizesna** [comment]
Kdybys chtěl / kdybyste kdokoli chtěli vymyslet nové texty nebo překopat ty staré, pomoc uvítám.

**Comment by malinajan** [comment]
Zkusím se na to podívat.

**Comment by malinajan** [comment]
Překopal jsem komplet úvodní texty.
