### ISSUE TITLE
Vacsie fotky orgov?

### ISSUE THREAD

**Issue by mukrop** [zverinec/kscuk-web#28]
Na velkom monitore (1600x900) su fotky orgov relativne male (130x100). Pri mensom rozliseni je to akurat, nezvazujeme ich pri vacsich rozliseniach ukazat vacsie?

**Comment by malinajan** [comment]
Mně osobně menší fotky na velkém monitoru nevadí.

**Comment by zvizesna** [comment]
Mně asi taky ne.

**Comment by Krejdom** [comment]
Já zastávám stejný názor jako Martin...

**Comment by malinajan** [comment]
Teď by měly být trošku větší, koukni na web.

**Comment by Krejdom** [comment]
Rozdíl jsem asi nepostřehla.
