### ISSUE TITLE
Stejný okraj obsahu a záhlaví a zápatí

### ISSUE THREAD

**Issue by Krejdom** [zverinec/kscuk-web#29]
Řešili jsme to, myslím, že to vypadá líp, když to není až do stran.

**Comment by malinajan** [comment]
Mně se zdá,že v současné době je stejný, ne?

Pokud vím, tak se řešení uzavřelo s tím, že je to Vendyno designérské rozhodnutí, třeba web Soba to tak má taky. Mně osobně současná verze navadí.

**Comment by Krejdom** [comment]
Obsah je užší než záhlaví a zápatí. Mně se to líbí víc, když je to stejně. Ale je to můj názor.

**Comment by malinajan** [comment]
Aha, sorry, já porovnávat jen záhlaví a zápatí... S Domčiným názorem spíš souhlasím, ale zároveň plně respekuji designérský návrh Vendy, já aktuální verzi s klidem na duši ukážu světu.

**Comment by zvizesna** [comment]
Řešili, ale nemůžu si pomoct, mně se to tak prostě nelíbí. Když menu navazuje rovnou na obsah, ještě se to nějak dá, ale když je pod ním velká fotka, která sahá od kraje ke kraji, přijde mi to hrozně divné.
