### ISSUE TITLE
Podtitulek s datem zaniká

### ISSUE THREAD

**Issue by Krejdom** [zverinec/kscuk-web#31]
Text:

> KSI & IBIS
> 
> 9.–16. 9. 2018 (od neděle do neděle)

Je málo výrazný, na to, jak je důležitý.

**Comment by malinajan** [comment]
(Podle mě je současný podtitulek v pohodě.)

**Comment by zvizesna** [comment]
Jak by sis ho představovala zvýraznit?
Na druhou stranu, text se ještě jednou zopakuje v sekci O co jde. Je tedy potřeba, aby byl výraznější?

**Comment by malinajan** [comment]
@Krejdom Co kdyby sis to zkusila upravit podle tvých představ a poslal nám tvůj návrh?

**Comment by malinajan** [comment]
Zavřeno z důvodu dlouhodobé neaktivity. V případě zájmu klidně znovu otevřít.
