### ISSUE TITLE
Méně barev

### ISSUE THREAD

**Issue by Krejdom** [zverinec/kscuk-web#32]
Můžeme z webu oddělat šedé věci?

- záhlaví udělat černé na bílém
- nápisy "O co jde? Kde? ..." Udělat třeba na střídačku zeleně/oranžově.
- Přihlašovací tlačítko udělat černé nebo kombinací zel/or a hlavně by bylo fajn, aby to vypadalo víc jako tlačítko (třeba aby to změnilo barvu po najetí (z oranžové na zelenou? z černé na oranžovou/zelenou?) nebo přidat nějaký rámeček?
- Nadpis "Organizátoři" stačí černě, mohlo by fajn nad ním zopakovat oddělovač, co je pod fotkou - jako oddělení sekce.
- Testy o organizátorech stačí černě.
- Zápatí zase černé na bílém a klidně nad ně hodit zase znovu ten oddělovač (opakující se prvky jsou fajn).

**Comment by malinajan** [comment]
> Můžeme z webu oddělat šedé věci?

Proč? Nelíbí se ti to? Nebo je ještě nějaký jiný důvod?

Já osobně s šedou nemám problém.

**Comment by Krejdom** [comment]
Grafická zásada viz třeba http://www.tigercolor.com/color-lab/tips/tip-01.html
Tady nám to komplikuje to, že chcem využívat KSI oranžovou a IBIS mentolovou, což už samo o sobě je dost zatěžující (a úplně nechceš dávat tam další odstíny těchto barev), čím míň dalších barev tam bude, tím líp.

**Comment by malinajan** [comment]
Ok, díky za info. Za mě je ta šedá ok.

**Comment by zvizesna** [comment]
Pokud má stránka standardní bílý základ a černé písmo, bílou a černou v návrhu jako plnohodnotné barvy nevnímám a ani s nimi tak nepočítám. Takže ta třetí barva je šedá. Oranžová a mentolová se v kombinaci můžou zdát moc divoké, a právě proto jsem k nim tu šedou vybrala. Hodí se k oběma a dobře je spojuje. (Což zase není nemožné, vzhledem k tomu, že jsou obě světlé a jasné.) 
Původní záměr byl dělat větší plochy (záhlaví, zápatí, tlačítko) neutrálně šedě, aby to moc neřvalo, a ty dvě výrazné barvy nechávat jen na menší plochy. Což se teď s přebarvením tlačítka pro jeho větší výraznost sice trochu rozbilo, ale pořád si myslím, že je ta šedá potřebná a hezká. Taky zastávám názor, že záhlaví a zápatí by mělo být v layoutech tohoto typu plné. A líbí se mi, když odliším typ/význam textu i barevně.
Takže promiň, ale s tímhle vážně nesouhlasím, ani mi aplikace toho pravidla nepřijde validní.

**Comment by Krejdom** [comment]
Ve volné chvíli (kéž by nějaké byla) to zkusím ještě namodelovat.
