### ISSUE TITLE
Text v registraci

### ISSUE THREAD

**Issue by Krejdom** [zverinec/kscuk-web#33]
- Sjednotit tykání/vykání.
- Vedlejší věta ", abychom ti mohli poslat další informace." mi nedává smysl.

Co třeba:
`Vyplň dotazník s údaji, které potřebujeme vědět před konáním K-SCUKu, abychom ti mohli poslat další informace.`

**Comment by malinajan** [comment]
Tohle by asi chtělo probrat v šírším kruhu orgů.

**Comment by Krejdom** [comment]
No aspoň to tykání tam může být hned, bez předchozích diskuzí, myslím.
