### ISSUE TITLE
Registrace: Přidat otázku na stravovací omezení

### ISSUE THREAD

**Issue by bsaid** [zverinec/kscuk-web#35]
Chceme přidat otázku na stravovací omezení do přihlášky?

**Comment by malinajan** [comment]
Já bych byl rozhodně pro. Strava je ve zdravodotazníku, ale to je na stravu už pozdě. Co si o tom myslí kuchař z minulého roku @mukrop?

**Comment by yaqwsx** [comment]
Jak dlouho před akcí vybíráme zdravodotazník?

**Comment by malinajan** [comment]
Týden před akcí (aby byly zdravotní informace aktuální).

**Comment by mukrop** [comment]
Ako kuchar by som rozhodne bol radsej mat to skor ako tyzden pred akciou. Ale v uvodnom dotazniku sa mi to zda celkom skoro -- ak mas komplikovanejsiu dietu, tak sa ti to nechce uplne podrobne rozpisovat do prveho anonymneho dotaznika -- alebo uz som paranoidny? (Fakt to neviem odhadnut.)

Osobne sa mi zda lepsie riesenie vyberat zdravodotaznik tak 2 tyzdne pred akciou a mat to len tam.

**Comment by malinajan** [comment]
Mně osobně vůbec navadí dát tuto informaci do úvodního dotazníku. Martinův komentář mi přijde paranoidní.

**Comment by mukrop** [comment]
To je za mna (z pohladu kuchara) tiez fajn riesenie (ktore navyse nevyzaduje posuvat fungujucu prax so zdravodotaznikmi).
