### ISSUE TITLE
Registrace: provzdušnit

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#38]
Zbavit se rámečkového designu ze starého webu. TextBoxy klidně na celý řádek, víz např. registraci v KSI. Obecně bych se nebál inspirovat registrací v KSI.

**Comment by malinajan** [comment]
(a hlavně to tlačítko nějak jinak -- třeba baervné, šedé, ale rozhodně ne to defaultní tlačítko...)

**Comment by malinajan** [comment]
Já bych to tu zavřel. @zvizesna, co říkáš?

**Comment by malinajan** [comment]
Done.

**Comment by zvizesna** [comment]
Ok. Ale oplakávám tlačítkové rohy. Enhancement to be.
