### ISSUE TITLE
B-týmáci?

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#42]
Zmínit, že na akci se objeví i další lidi mimo organizátorů na úvodní stránce? Já bych osobně byl třeba pro větu typu "Na akci se objeví i další organizátoři.", či nějak lépe přeformulovat.

**Comment by yaqwsx** [comment]
Za mě blbost. Pokud chceš být hyperkorektní, tak na hlavní stránku místo "Organizátoři" napiš "Akci pro vás připravují:"

**Comment by malinajan** [comment]
Ok, asi blbost.
