### ISSUE TITLE
Registrace: zkušenosti s podobnými akcemi?

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#43]
Pro přizpůsobení náročnosti programu se může hodit vědět, jestli mají účastníci zkušenosti s akcemi podobného typu. Co takhle přidat do registrace otázku "Byli jste už na nějakém podobném soustředění? Na jakém?".

**Comment by yaqwsx** [comment]
Jsem pro

**Comment by malinajan** [comment]
Co si o tomto myslí @Krejdom a @mukrop?

**Comment by Krejdom** [comment]
Nejsem proti.

**Comment by mukrop** [comment]
Kludne. Naco vam tato informacia bude?
(Je to basnicka otazka, odpoved sem nemusite pisat -- ide mi len o to, ci je vam to treba.)

**Comment by malinajan** [comment]
Abych se přiznal, mým cílem není vědět, na kolika byli ŠMFkách, ale znát odpověď na otázku *Jakou zátěž vydržíš?*, abych mohl uzpůsobovat náročnost programu nebo třeba vybírat rovnoměrně do lidi do týmů. Tajně doufám, že podle odpovědí na otázku *zkušenosti s podobnými akcemi* dokážu posoudit, na co jsou zvyklí a kolik jim toho můžu naložit.

**Comment by malinajan** [comment]
Done.
