### ISSUE TITLE
Vyladit zobrazení zdravodeklarace.

### ISSUE THREAD

**Issue by zvizesna** [zverinec/kscuk-web#48]

**Comment by malinajan** [comment]
Zkontroloval jsem, že se zdravodeklarace zobrazí a lze ji vyplnit. Ještě je třeba zkontrolovat, že se skutečně vygeneruje.

**Comment by malinajan** [comment]
FYI: zdravodeklarace funguje, vyplnění ok, stáhnutí pdf ok.

**Comment by malinajan** [comment]
Faktické připomínky od @Krejdom:

 * [x] Oddělat ze zdravodeklarace stravovací omezení (vyplnili už v přihlášce)
 * [x] Upřesnit, co to znamená *V případě nutnosti podejte zprávu*.
 * [x] Tykat (třeb i v úvodním odsstavci nahoře se tyká).
 * [x] Přidat volné místo před submit tlačítko.

**Comment by malinajan** [comment]
Hotovo.
