### ISSUE TITLE
Nefunguje stahování kompletních zdravodeklarací

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#5]

**Comment by malinajan** [comment]
... podle inspekce nikdy nefungovalo.

**Comment by zvizesna** [comment]
Případně přidat k uživateli tlačítko na stáhnutí zdravodeklarace.

**Comment by malinajan** [comment]
Podle mě by bylo super mít obojí, viz #51. Komplet zdravodeklarace se hodí před akcí, když chceš vytisknout všechny pro případ, že ji někdo zapomene.

**Comment by zvizesna** [comment]
Ok, nebylo to myšleno jako xor. Jenom jsem připisovala obsah tvé zprávy s návrhem funkcionality, aby to bylo pěkně pohromadě.

**Comment by zvizesna** [comment]
Make downloading zipped declarations work. [1ed0e652a04bd078ece999d97e64127dac59512f ](https://github.com/zverinec/kscuk-web/commit/1ed0e652a04bd078ece999d97e64127dac59512f)

(Remove unneccessary Zippy. [c547ed343d91266957ca9b82d92a8ec46aa613b7](https://github.com/zverinec/kscuk-web/commit/c547ed343d91266957ca9b82d92a8ec46aa613b7),
Remove unneccessary healthdeclaration placehoder file and folder. [7288f5b6c82b0a8e25aeb601bd06cbf151fd571f](https://github.com/zverinec/kscuk-web/commit/7288f5b6c82b0a8e25aeb601bd06cbf151fd571f))
