### ISSUE TITLE
Chceme zdravodeklarace tisknout my, nebo je mají tisknout účastníci?

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#50]
Ahoj,

po vyplnění zdravodeklarace se teď vypíše něco jako "vtiskněte si toto pdf a přineste ho na akci". Chceme to tak skutečně dělat? Nechceme prostě vytisknot všechny my (orgové), abychom eliminovali případ, že ji někdo nepřinese?

Věci ke zvážení: na místě často bývá internet a tiskárna, takže případnou chybějící deklaraci lze stáhnout. Pokud nebývá internet, má ho alespoň nějaký org v mobilu po cestě, takže i když na bjektu není signál, může ji stáhnout uložit a na místě ak vytisknout.

**Comment by malinajan** [comment]
Fakt: chceme, aby zdravodeklaraci podepisovali rodiče. Takže si to maji asi tisknout sami, co?

**Comment by mukrop** [comment]
Ak ma byt podpisana od rodicov, tak nemate na vyber, Ak vam staci, ze si ju podpisu sami (alebo ju nepotrebujete podpisanu), tak je praktickejsie, aby ste si to tlacili sami.

**Comment by malinajan** [comment]
Minimálně u plnoletých bych podpis rodičů určitě nevyžadoval. Co myslíte, má smysl nechat si podepisovat u neploletých (reálně se tu bavíme o 15+) zdravodeklaraci od rodičů?

**Comment by mukrop** [comment]
Podla mna nie, ale neviem, ako je to pravne.

**Comment by malinajan** [comment]
@Krejdom @yaqwsx Co myslíte, má smysl nechat si podepisovat u neploletých (reálně se tu bavíme o 15+) zdravodeklaraci od rodičů?

**Comment by Krejdom** [comment]
Raději bych to nechávala podepsat rodiči.

**Comment by malinajan** [comment]
Ok, tak se budou nechávat podepisovt rodiči.
