### ISSUE TITLE
Vycentrovat jména orgů?

### ISSUE THREAD

**Issue by malinajan** [zverinec/kscuk-web#9]
Navrhuji vertikálně vystředit jména orgů dohromady s jejich itro textem do steřdu fotografie. Když bude mít org 3 řádky textu, nebude to vyapdat hezky, ale to snad zvládneme pořešit tak, aby měl bždy 2.

**Comment by zvizesna** [comment]
Fajn, udělám takovou verzi a vyzkoušíme si to.

**Comment by malinajan** [comment]
Done.
